# Generated by Django 2.2 on 2019-05-05 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Slug',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
    ]
