# Generated by Django 2.2 on 2019-08-04 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190507_1115'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
